### PR TITLE
Fix usage of includes in node 4.6.0

### PR DESCRIPTION
**Pull request by hung-phan**
This PR is to use the method indexOf instead of includes for the reason that it doesn't work with the node 4.6.0 yet and causes error in server after the update.

```
[2016-09-29 23:12:10.592] [INFO] console -   xxx GET / 500 13ms -
  error TypeError: _this.opts.excludedMethods.includes is not a function
    at CSRF.middleware (/Users/hungphan/Desktop/workarea/koa-react-isomorphic/node_modules/koa-csrf/lib/index.js:39:36)
```

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -51,7 +50,7 @@ export default class CSRF {
 
     ctx.response.__defineGetter__('csrf', () => ctx.csrf);
 
-    if (this.opts.excludedMethods.includes(ctx.method))
+    if (this.opts.excludedMethods.indexOf(ctx.method) !== 1)
```
Comment (niftylettuce) [inline src/index.js]: Can you please fix this so that it is `-1` instead?

Therefore, if the position is not `-1`, then that means it must be found.

Arrays start with key 0, not 1, but it should be -1 anyways.

Comment (hung-phan) [inline src/index.js]: Oh sorry, typo. Updating

**Comment by hung-phan** [comment]
@niftylettuce Updated

**Comment by popomore** [comment]
It should be merged to 2.x, 3.x is for koa@2 that support aa, []. includes is also supported 😄 .

**Comment by hung-phan** [comment]
What is the node version you are using to run @popomore?

**Comment by popomore** [comment]
aa is supported by node@6 with harmony flag

**Comment by hung-phan** [comment]
I don't use node@6 with harmony flag. I use node@4 and use a transpiler on my modules. What is the best practice for koa.js then? 🤔

**Comment by popomore** [comment]
Sorry, I don't use transpiler on server side. LGTM for me now. Add node@4 to travis for testing?

**Comment by hung-phan** [comment]
Updated

**Comment by hung-phan** [comment]
@popomore, @niftylettuce.

**Comment by niftylettuce** [comment]
I've published 3.0.4 to NPM.  @hung-phan any chance you could also update the History file?

**Comment by hung-phan** [comment]
ok @niftylettuce
